
[FIREBASE]
type = "service_account"
project_id = "login1-e7ab2"
private_key_id = "db96ca50332dd783fe7a943c357b72bf4fc176d5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRUgetUhJkPpQE
rqXnpGhPTly9uaaJzd9QTrYxhANlfLJJV01eVo3T7zPsKEmnDrGVNuIoefI9f+/s
5UsJwUmXvzBXVNpd5rqVqrgCZ1DuW0H0WaA3xDxR/WfuGYBvisKjteju3bdmSUFO
YrH+ORd9QlY1smol3DMlrXz06letSnLMeCRxBI2mwaIRyDB3wWixKxeAqCrP6qaD
wr05O8yJRvTb7fWiDbO+g+DEzi43zOQLB8WviLG4UrU16NMdj4D8Evo5MgiXhXdJ
COzoFoUHt1gToySqg93zNKnamq3NYvHfEJT05YFZc+Bw9JY6aSji198NnQxzF7UF
lc24isqNAgMBAAECggEAA0NccUbtQyN37+wVFAZhGz4P02QDL59w/XHXWfBCk/Yc
sBNXVm18/90jxGkLCjqqvrZrUibh2t7qtkO2JsHHoZZObPNwBV9lGz4yaNSEKM3C
unTHOvdT2ryw6RT8BpZ1hah+qB1MEEvQuSXFZpQsmeb11xfKmyp9SvdoZ50GSYzv
WBODpvsyDiIchUixaHMdTpZeu2F8zAFvHvM/TVbMwf/TjLxXW8LQc5OCKMakszzi
siXbBonD5IVAFi0MP+2Quv5BzvrIn51z03dcRdHGp6SO9Srx+qPbOwW4TpakeqnW
KOxmXB7zstroS8JpC9jDJeiaDL7SsfVgi7L1Hwg9IQKBgQDuY/aZfxmK/aCZbHkS
puZs1x8y6nlYkifgTPiiXdzYUqQ87iCc4IerjrnVawtWSQy2KM779EiAqEyBHZOE
48Eawd2bOb02d9xqRDkOuIbwSNVjdcb1UZLQuwz62cs6lmdeKRM26ZaeAgoVmOQI
TnnAnaZyMXFYqHD8U1v0CfwTNQKBgQDgyFfZVUQJmCHJ52gAC7EzDVPPbx9TKWge
kbztsNTy2AYkHkXuZ5vcqBLGtNnxmqmk+uPicHdK94QWq+LFgO5kFTXsApC7znTS
UnE3rZX6Hzcqjtmkd82WJR+/9vebpafuOiaj/XLZMy3eOLENUHZMn3YXlDSHaWlf
ToopXbMs+QKBgQCEXWLeZdEj+KHErpMnRR6qjmPXXJPWFwknJPXlCaMHRhPFdR8M
nCsYmd4bXx1jYpo5Rr1u7nuXXFtmUarIXcGp/rzyZIPoC3OKWakowFLEdlxtpka7
jfisB0A0xNtwA3UPtlTh559mypEY3tS2vAQkbCSwQT3DUXuyzwI+pZCehQKBgQDT
hBIOQ0rLkGkzGVpmuJncxUy5JAKg+ZStN0xFiiFIBnj44bfCV6J1p35LlwCCdZvu
z9tCR7wpQfH8d2/jk6g/ayobVGqnHuYUx1kcIG7BN0Bs/pDUT5uYDoTq2VU0FFSK
OhQEOkkpExy1QDlyouU+wsqX83DefxWVhk1CEZa52QKBgGf2PQXH3nZw8y1qmtiB
PxUtae2hFnUV4QnftNFAeIkLxEgfe5b/xGcFWc1GiB8/XqFX2t4fupnwnUQ2iiUc
bwi71Yis20to6nwfBl/VgW7P9KPkzDAMktXmJ2sb86mqjl/nrohYQOG6akXtzDVT
MseNy+yPlJ6k45tdIMcl4VSo
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@login1-e7ab2.iam.gserviceaccount.com"
client_id = "113780619554387369019"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40login1-e7ab2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

web_api_key = "AIzaSyCj0UPv444P-C6ggFZ8Q_NXvSSBraHeDG4"
